feat: script for analyzing test coverage
summer-research-program/ExtendingCodeNetTests pull request #1
Opened 2024-06-12 17:14 UTC by pranit-sinha

Adds a script, to be run from top level directory as so: `python src/coverage/test_coverage_analyzer.py`, for listing all files for which current test cases achieve <100% coverage.

- Directory names are hardcoded according to directory structure at time of commit, viz.

```
├── dataset
│   ├── Code
│   ├── TestCases
└── src
    └── coverage
```

- [ ] All gcov artifacts are currently produced inside dataset/Code. Slightly non-trivial to alter this behavior, can fix in some time - meanwhile, use "rm *.gcda *.gcno *.gcov" inside that directory to clean everything out.

2024-06-12 19:52 UTC, darko-marinov requested changes
A good starting script (although Python is much more verbose than Bash for some of these things). We should still see if we can make the script smaller.

2024-06-12 19:52 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +    for i in range(len(files)):
Why introduce `i` rather than `for file in files:`.

2024-06-12 19:52 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +        flags = "--coverage -O0" + (" -lm" if lm_flag else "")
Why not add `-lm` always?

2024-06-12 19:52 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +        p = Popen(['gcov', files[i]], cwd='dataset/Code', stdin=PIPE, stdout=PIPE, stderr=PIPE)
You likely need to delete old GCov files (`.gcno` and `.gcda`??) as otherwise coverage will accumulate from previous runs.

2024-06-12 19:52 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +        for j in range(len(lines)):
Can this loop be smaller? How does the output of `gcov` look like? Does `Lines executed` repeat many times, and you really need just the line after `File '`?

2024-06-13 09:28 UTC, pranit-sinha commented
Thank you for the review, Darko - your suggestions have been implemented and have reduced the lines of code.

2024-06-13 13:08 UTC, mrigankpawagi requested changes

2024-06-13 13:08 UTC, mrigankpawagi commented on src/coverage/test_coverage_analyzer.py
> +            if coverage < 100.0:
Can we just create a map `{file: coverage%}` and dump it to some JSON file so that we can later on filter things as we like (for example, we may want to filter for `<98%` at some point but for that we would have to rerun the script)?

Edit: Ok maybe we don't have to rerun coverage since it seems the `.gcov` files have that information. It would still be good to not hardcode `100` in the filter. It would also be good to allow running the script on a single file.

2024-06-13 15:50 UTC, darko-marinov reviewed
The script looks much cleaner now. Still can be simplified further for the existing functionality. If you want to add processing for only one file, it'd require more functionality.

2024-06-13 15:50 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +        subprocess.run(f"rm dataset/Code/{filebase}.gcda dataset/Code/{filebase}.gcno", check=False, capture_output=True, shell=True, timeout=30)
Better do this before running the program (maybe with `rm -f`) than after.

2024-06-13 15:50 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +            if coverage < 100.0:
Agree. Maybe just simple CSV: `if "Lines executed" in lines[1]: print(file + "," + lines[1].split(':')[1].split('%')[0])`.

2024-06-13 17:16 UTC, pranit-sinha commented
The script now supports specifying an input directory/input files to run over, as well as a coverage parameter. It also outputs the coverage rate for all input files as CSV, while still separately outputting the list of files that fail to meet the coverage parameter.

2024-06-13 18:14 UTC, darko-marinov reviewed
I'm fine to have this accepted whenever you need it, just make sure to merge with the other script for computing outputs.

2024-06-13 18:14 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +    for file in files:
Please extract this main logic into a new function that takes as input `files` and then computes a dictionary mapping file name to coverage.

2024-06-13 18:14 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +if __name__ == "__main__":
This is a good starting point for processing command-line args but should be merged with the other script for checking outputs.

2024-06-13 18:14 UTC, darko-marinov commented on src/coverage/test_coverage_analyzer.py
> +    print("Tests for the following files achieved less than the desired coverage. For further information, read the .gcov files produced in the code directory.")
You don't need to take a limit and print only those files. Simply compute coverage for all files and return a dictionary for that. Someone else can filter if needed. If you want to print something, print the dictionary (as CSV or JSON).

2024-06-16 15:25 UTC, pranit-sinha commented
All requested changes have been made; further, @Shofiya2003 will create a new PR in this repository to upload her script and the shared script. Since no further edits are required here to allow that, I hope it's okay to merge this.

2024-06-16 15:26 UTC, merged

2024-06-16 16:18 UTC, darko-marinov commented
Fine with me to merge!